insert into Movies (Title,DateRel,SubCategory,Director,Link1) values
('Chronicle','2011','Thriller','Duncan Jones','http://www.imdb.com/title/tt1706593/?ref_=fn_al_tt_1'),
('Source Code','2012','Action drama','Josh Trank','http://www.imdb.com/title/tt0945513/?ref_=fn_al_tt_1'),
('Cloud Atlas','2012','Drama','Tom Tykwer, The Wachowskis','http://www.imdb.com/title/tt1371111/?ref_=fn_al_tt_1'),
('Looper','2012','Thriller','Rian Johnson','http://www.imdb.com/title/tt1276104/?ref_=fn_al_tt_1'),
('Prometheus','2012','Action,Horror','Ridley Scott','http://www.imdb.com/title/tt1446714/?ref_=fn_al_tt_1'),
('Safety Not Guaranteed','2012','Comedy drama','Colin Trevorrow','http://www.imdb.com/title/tt1862079/?ref_=fn_al_tt_1'),
('The Congress','2013','Animation','Ari Folman','http://www.imdb.com/title/tt1821641/?ref_=fn_al_tt_1'),
('Elysium','2013','Action','Neill Blomkamp','http://www.imdb.com/title/tt1535108/?ref_=fn_al_tt_1'),
('Gravity','2013','Drama','Alfonso Cuarón','http://www.imdb.com/title/tt1454468/?ref_=fn_al_tt_1'),
('Her','2013','Drama','Spike Jonze','http://www.imdb.com/title/tt1798709/?ref_=fn_al_tt_1'),
('Oblivion','2013','Post-apocalyptic','Joseph Kosinski','http://www.imdb.com/title/tt1483013/?ref_=fn_al_tt_1'),
('Pacific Rim','2013','Monster movie','Guillermo del Toro','http://www.imdb.com/title/tt1663662/?ref_=fn_al_tt_1'),
('Snowpiercer','2013','Action thriller','Bong Joon-ho','http://www.imdb.com/title/tt1706620/?ref_=fn_al_tt_1'),
('The Zero Theorem','2013','Drama,Fantasy','Terry Gilliam','http://www.imdb.com/title/tt2333804/?ref_=fn_al_tt_1'),
('Mr.Nobody','2009','Drama Fantasy Romance','Jaco Van Dormael','http://www.imdb.com/title/tt0485947/?ref_=nv_sr_1'),
('V for Vendetta','2006','dystopian political thriller','James McTeigue','http://www.imdb.com/title/tt0434409/?ref_=fn_al_tt_1'),
('Avatar','2009',' epic science fiction film','James Cameron','http://www.imdb.com/title/tt0499549/?ref_=nv_sr_1'),
('A.I. Artificial Intelligence','2001','science fiction drama','Steven Spielberg','http://www.imdb.com/title/tt0212720/?ref_=fn_al_tt_1'),
('Donnie Darko','2001','psychological horror-science fiction drama','Richard Kelly','http://www.imdb.com/title/tt0246578/?ref_=fn_al_tt_1'),
('The Butterfly Effect','2004','psychological thriller','Eric Bress and J. Mackye Gruber','http://www.imdb.com/title/tt0289879/?ref_=fn_al_tt_1link'),
('Vanilla Sky','2001','science fiction psychological thriller','Cameron Crowe','http://www.imdb.com/title/tt0259711/?ref_=fn_al_tt_1'),
('The Island','2005','science fiction-action film','Michael Bay','http://www.imdb.com/title/tt0399201/?ref_=fn_al_tt_1'),
('The Day After Tomorrow','2004','climate science fiction disaster film','Roland Emmerich','link'),
('The Fountain','2006','epic drama film','Darren Aronofsky','http://www.imdb.com/title/tt0414993/?ref_=fn_al_tt_1'),
('Children of Men','2006','science fiction thriller','Alfonso Cuaron','http://www.imdb.com/title/tt0206634/?ref_=fn_al_tt_1'),
('Equilibrium','2002','science fiction film','Kurt Wimmer','http://www.imdb.com/title/tt0238380/?ref_=fn_al_tt_1')
